# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1+np.exp(-x))
def relu(x):
    return np.maximum(0,x)
def tanh(x):
    return np.tanh(x)
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x))

x=np.linspace(-10,10,100)
print(x)

fig,axs=plt.subplots(2,2,figsize=(15,10))
axs[0,0].plot(x, sigmoid(x))
axs[0,0].set_title("SIGMOID")

axs[0,1].plot(x, relu(x))
axs[0,1].set_title("RELU")

axs[1,0].plot(x, tanh(x))
axs[1,0].set_title("TANH")

axs[1,1].plot(x, softmax(x))
axs[1,1].set_title("SOFTMAX")
plt.suptitle('ACTIVATION FUNCTIONS')

plt.show()


"""  
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1/(1+np.exp(-x))

x= np.linspace(-10,10,100)

y=sigmoid(x)

plt.title("sigmoid")
plt.plot(x,y)


"""

