# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Flatten,Dense
from keras.datasets import mnist

(X_train,y_train),(X_test,y_test)=mnist.load_data()
X_train=X_train / 255.0
X_test=X_test / 255.0

model=Sequential([
    Flatten(input_shape=(28,28)),
    Dense(128,activation='relu'),
    Dense(10,activation='softmax')
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=10,batch_size=64)
loss,accuracy=model.evaluate(X_test,y_test)
print("LOSS ",loss)
print("ACCURACY ",accuracy)

