# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np

def threshold_binary(dot,T):
    if dot>=T:
        return 1
    else:
        return 0

input_array=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
weights=np.array([1,-1])
T=1
product=input_array @ weights
print("INPUT ARRAY: ",input_array)
print("PRODUCT: ",product)

print("ACTIVATION")
for i in range(0,4):
    activation_fn=threshold_binary(product[i],T)
    print(activation_fn)

