# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np
import sklearn as skl
from sklearn.linear_model import Perceptron

input_array=np.array([
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,1,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
])

label=np.array([1,-1,1,-1,1,-1,1,-1,1,-1])
perceptron=Perceptron(max_iter=100,tol=None)
perceptron.fit(input_array,label)
Perceptron(max_iter=100,tol=None)

for i in input_array:
    pr=perceptron.predict([i])
    if pr==1:
        print(i,"EVEN")
    else:
        print(i,"ODD")

