# -*- coding: utf-8 -*-
"""sigmoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IN1bI1uzIr_wuaMnqynSrWQIkTcYV1tn
"""

import numpy as np

x1=np.array([1,1,1,-1])
y1=np.array([1,-1])
x2=np.array([-1,-1,1,1])
y2=np.array([-1,1])
W=np.outer(y1,x1)+np.outer(y2,x2)

def bam(x):
    y= W @ x
    return np.where(y>=0,1,-1)

x_test=np.array([1,-1,-1,-1])
y_test=bam(x_test)

print("INPUT: ",x_test)
print("OUTPUT: ",y_test)

